name: mi_app_flutter
description: "Pet Match - AplicaciÃ³n para encontrar mascotas perdidas"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase habilitado para usar con Google Sign-In
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^4.10.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.0.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  js: ^0.6.7
  http: ^1.2.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png

  fonts:
    - family: AntonSC
      fonts:
        - asset: assets/fonts/AntonSC-Regular.ttf
